#!/bin/bash

source "/etc/archconfig/settings.conf"
source "$ARCHCONFIG_PATH/$FUNCTIONS_FILE" "$CUSTOMIZE_SCRIPT_LOG_FILE"

executeScript "$ARCHCONFIG_PATH/$UPDATE_PACKAGE_LIST_FILE"
executeScript "$ARCHCONFIG_PATH/$CONFIGURE_PACMAN_FILE"
executeScript "$ARCHCONFIG_PATH/$INSTALL_PACKAGES_FILE"
executeScript "$ARCHCONFIG_PATH/$LOAD_GUEST_MODULES_FILE"
executeScript "$ARCHCONFIG_PATH/$COPY_CONFIG_FILES_FILE"
executeScript "$ARCHCONFIG_PATH/$INSTALL_DWM_FILE"
executeScript "$ARCHCONFIG_PATH/$SET_TERMINAL_VIDEO_MODE_FILE"
executeScript "$ARCHCONFIG_PATH/$DISABLE_SYSLINUX_MENU_FILE"
executeScript "$ARCHCONFIG_PATH/$SET_EARLY_TERMINAL_FONT_FILE"
executeScript "$ARCHCONFIG_PATH/$RECREATE_IMAGE_FILE"

