#!/bin/bash

source "settings.conf"
source "$FUNCTIONS_FILE"

source "$UPDATE_PACKAGE_LIST_FILE"
source "$CONFIGURE_PACMAN_FILE"
source "$INSTALL_PACKAGES_FILE"
source "$LOAD_GUEST_MODULES_FILE"
source "$DOWNLOAD_CONFIG_FILES_FILE"
source "$INSTALL_DWM_FILE"
source "$SET_TERMINAL_VIDEO_MODE_FILE"
source "$DISABLE_SYSLINUX_MENU_FILE"
source "$SET_EARLY_TERMINAL_FONT_FILE"
source "$RECREATE_IMAGE_FILE"

