#!/bin/bash

### ### ### ### ### ### ### ### System settings

### ### ### ### Disks and partitions

PARTITION_PREFIX="/dev/"

### ### Root partition

# Disk on which root partition will be created, without partition number
# e.g. "sda"
ROOT_PARTITION_HDD="sda"

# Partition nb on ROOT_PARTITION_HDD where root partition will be created
# e.g. for /dev/sda2 - "2"
ROOT_PARTITION_NB="2"

# Size of root partition. Format as for fdisk.
# e.g. for 1 GB "+1G", for remaining space ""
ROOT_PARTITION_SIZE=""

# Root partition file system. Format as for mkfs.XXX
ROOT_PARTITION_FS="ext4"

# Directory on live cd session where root partition will be mounted
ROOT_PARTITION_MOUNT_POINT="/mnt"

### ### Swap partition

# Disk on which swap partition will be created, without partition number
# e.g. "sda"
SWAP_PARTITION_HDD="sda"

# Partition nb on SWAP_PARTITION_HDD where swap partition will be created 
# e.g. for /dev/sda1 - "1"
SWAP_PARTITION_NB="1"

# Size of swap partition. Format as for fdisk.
# e.g. for 1 GB "+1G", for remaining space ""
SWAP_PARTITION_SIZE="+1G"

### ### Boot partition

# Disk on which boot partition will be created, without partition number
# e.g. "sda"
BOOT_PARTITION_HDD="sda"

# Partition nb on BOOT_PARTITION_HDD where boot partition will be created 
# e.g. for /dev/sda1 - "1"
BOOT_PARTITION_NB="2"

# Size of boot partition. Format as for fdisk.
# e.g. for 1 GB "+1G", for remaining space ""
BOOT_PARTITION_SIZE="+1G"

### ### ### ### Base system

BASE_SYSTEM_PACKAGES="base base-devel"

### ### System config

HOST_NAME="archon"

### ### Localization

### Languages

LOCALIZATION_LANGUAGE1="en_US.UTF-8"
LOCALIZATION_LANGUAGE2="pl_PL.UTF-8"

### Time zone

LOCALIZATION_TIME_ZONE="Europe/Warsaw"

### HW clock

LOCALIZATION_HW_CLOCK="--systohc --utc"

### ### Console

### Keymap

CONSOLE_KEYMAP="pl"

### Font

CONSOLE_FONT="Lat2-Terminus16"

### ### Network

### Service

NETWORK_SERVICE="dhcpcd"

### Wired interface

NETWORK_INTERFACE_WIRED="enp0s3"

### ### Bootloader

BOOTLOADER_PACKAGE="syslinux"

### ### ### ### ### ### ### ### Customization settings

### ### ### ### Regular user setup

USER_NAME="adam"
USER_MAIN_GROUP="users"
USER_ADDITIONAL_GROUPS="wheel,storage,power"
USER_SHELL="/bin/bash"
USER_HOME="/home/$USER_NAME"

### ### Bash dotfiles

### bashrc

DOTFILE_BASHRC=".bashrc"

### bash_profile

DOTFILE_BASH_PROFILE=".bash_profile"

### ### ### ### Basic tools

### ### vim

### Packages

VIM_PACKAGES="vim"

### Dotfiles

DOTFILE_VIM=".vimrc"
DOTFILE_VIM_COLORS_SOLARIZED_PATH=".vim/colors"
DOTFILE_VIM_COLORS_SOLARIZED_FILE="solarized.vim"

### ### ### ### Sound

ALSA_PACKAGES="alsa-utils"

### ### ### ### Xorg

### ### Xorg basic

XORG_BASIC_PACKAGES="xorg-server xorg-server-utils xorg-xinit"
XINITRC_DOTFILE=".xinitrc"

### ### Xorg additional

XORG_ADDITIONAL_PACKAGES="mesa"

### ### ### ### GUI tools etc

### ### Terminal

RXVTUNICODE_PACKAGES="rxvt-unicode"

### ### Font(s)

GUI_FONT_PACKAGES="ttf-inconsolata ttf-dejavu"

### ### WM-related

### dwm

# Dir to contain cloned git repository for dwm, etc
DWM_BUILD_PATH="/home/$USER_NAME/Building/dwm"

# Command to be launched by dwm when terminal shortcut is launched
TERMINAL_EMULATOR_COMMAND="urxvt"

### dmenu

DMENU_PACKAGES="dmenu"

### ### ### ### Development etc

### ### Version control

GIT_PACKAGES="git"
GIT_DOTFILE=".gitconfig"

### ### ### ### VirtualBox

### ### Guest utils

VIRTUALBOX_GUEST_UTILS_PACKAGES="virtualbox-guest-utils"

# Modules to be loaded during startup (modprobe)
VIRTUALBOX_GUEST_UTILS_MODULES="vboxguest vboxsf vboxvideo"

# Configuration file for loading modules during startup
VIRTUALBOX_GUEST_UTILS_MODULES_FILE="/etc/modules-load.d/virtualbox.conf"

### ### ### ### Misc config

# VGA mode to be used for console after boot
BOOTLOADER_VGA_MODE="864"

# Kernel params passed by bootloader during boot
BOOTLOADER_KERNEL_PARAMS="rw vga=$BOOTLOADER_VGA_MODE quiet"

### ### Issue

# Welocme message when logging in to console
CONSOLE_WELCOME_FILE="/etc/issue"
CONSOLE_WELCOME_MSG=""

### ### ### ### ### ### ### ### Archconfig settings

### ### ### ### Archconfig files

ARCHCONFIG_SETTINGS_FILE="settings"
ARCHCONFIG_FUNCTIONS_FILE="functions"
ARCHCONFIG_INSTALL_FILE="install"
ARCHCONFIG_CUSTOMIZE_FILE="customize"

### ### ### ### Archconfig paths

### ### New system location for archconfig files
ARCHCONFIG_PATH="$ROOT_PARTITION_MOUNT_POINT/root/archconfig"

### ### Dotfiles

### Dotfiles repository
DOTFILES_REPOSITORY_PROTOCOL="https"
DOTFILES_REPOSITORY_RAW_ADDRESS="raw.github.com"
DOTFILES_REPOSITORY_USER_NAME="lypant"
DOTFILES_REPOSITORY_REPO_NAME="dotfiles"
DOTFILES_REPOSITORY_BRANCH_NAME="simplified"
DOTFILES_REPOSITORY_RAW_URL="$DOTFILES_REPOSITORY_PROTOCOL://$DOTFILES_REPOSITORY_RAW_ADDRESS/$DOTFILES_REPOSITORY_USER_NAME/$DOTFILES_REPOSITORY_REPO_NAME/$DOTFILES_REPOSITORY_BRANCH_NAME"

### Dotfiles directories
DOTFILES_DIR_NAME="dotfiles"
DOTFILES_DIR_PATH="$USER_HOME/$DOTFILES_DIR_NAME"
DOTFILES_BACKUP_DIR="$DOTFILES_DIR_PATH/backup"


### ### ### ### Archconfig logs

ARCHCONFIG_LOG_PREFIX="AC: "

### ### ### ### LiveCD

# Number of mirrors to be found by rankmirrors
MIRROR_COUNT=5

