#!/bin/bash

sudo cp "$ARCHCONFIG_PATH/$VIRTUALBOX_CONFIG_FILE" "/etc/modules-load.d/virtualbox.conf"
sudo cp "$ARCHCONFIG_PATH/$ISSUE_FILE" "/etc/issue"

cp "$ARCHCONFIG_PATH/$BASH_PROFILE_PATH" "$USER_HOME_PATH/.bash_profile"
cp "$ARCHCONFIG_PATH/$BASHRC_FILE" "$USER_HOME_PATH/.bashrc"
cp "$ARCHCONFIG_PATH/$GITCONFIG_FILE" "$USER_HOME_PATH/.gitconfig"
cp "$ARCHCONFIG_PATH/$VIMRC_FILE" "$USER_HOME_PATH/.vimrc"
cp "$ARCHCONFIG_PATH/$VIM_SOLARIZED_FILE" "$USER_HOME_PATH/.vim/colors/solarized.vim"
cp "$ARCHCONFIG_PATH/$XDEFAULTS_FILE" "$USER_HOME_PATH/.Xdefaults"
cp "$ARCHCONFIG_PATH/$XINITRC_FILE" "$USER_HOME_PATH/.xinitrc"

