#!/bin/bash

DST_DIR=$1

# Destination paths - only for user-launchable scripts
GET_DST="$DST_DIR/$GET_FILE"
INSTALL_DST="$DST_DIR/$INSTALL_FILE"
CUSTOMIZE_DST="$DST_DIR/$CUSTOMIZE_FILE"

# Main directory
downloadFile "file://$ISO_ARCHCONFIG_PATH/$GET_FILE" "$GET_DST"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SETTINGS_FILE" "$DST_DIR/$SETTINGS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$INSTALL_FILE" "$INSTALL_DST"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CUSTOMIZE_FILE" "$CUSTOMIZE_DST"

# Utils
downloadFile "file://$ISO_ARCHCONFIG_PATH/$FUNCTIONS_FILE" "$DST_DIR/$FUNCTIONS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$DOWNLOAD_FILE" "$DST_DIR/$DOWNLOAD_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$COPY_FILE" "$DST_DIR/$COPY_FILE"

# Base

# Disk
downloadFile "file://$ISO_ARCHCONFIG_PATH/$PARTITION_DISKS_FILE" "$DST_DIR/$PARTITION_DISKS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CREATE_FILE_SYSTEMS_FILE" "$DST_DIR/$CREATE_FILE_SYSTEMS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$MOUNT_PARTITIONS_FILE" "$DST_DIR/$MOUNT_PARTITIONS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$UNMOUNT_PARTITIONS_FILE" "$DST_DIR/$UNMOUNT_PARTITIONS_FILE"

# Pacman
downloadFile "file://$ISO_ARCHCONFIG_PATH/$UPDATE_ISO_PACMAN_FILE" "$DST_DIR/$UPDATE_ISO_PACMAN_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$RANK_MIRRORS_FILE" "$DST_DIR/$RANK_MIRRORS_FILE"

# System
downloadFile "file://$ISO_ARCHCONFIG_PATH/$INSTALL_BASE_SYSTEM_FILE" "$DST_DIR/$INSTALL_BASE_SYSTEM_FILE"

# Fstab
downloadFile "file://$ISO_ARCHCONFIG_PATH/$GENERATE_FSTAB_FILE" "$DST_DIR/$GENERATE_FSTAB_FILE"

# Chroot

# Chroot
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CHROOT_FILE" "$DST_DIR/$CHROOT_FILE"

# Host name
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_HOST_NAME_FILE" "$DST_DIR/$SET_HOST_NAME_FILE"

# Localization

# Set locales
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_LOCALES_FILE" "$DST_DIR/$SET_LOCALES_FILE"

# Generate locales
downloadFile "file://$ISO_ARCHCONFIG_PATH/$GENERATE_LOCALES_FILE" "$DST_DIR/$GENERATE_LOCALES_FILE"

# Set language
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_LANGUAGE_FILE" "$DST_DIR/$SET_LANGUAGE_FILE"

# Set time zone
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_TIME_ZONE_FILE" "$DST_DIR/$SET_TIME_ZONE_FILE"

# Set hw clock
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_HW_CLOCK_FILE" "$DST_DIR/$SET_HW_CLOCK_FILE"

# Console

# Set console keymap
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_CONSOLE_KEYMAP_FILE" "$DST_DIR/$SET_CONSOLE_KEYMAP_FILE"

# Set console font
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_CONSOLE_FONT_FILE" "$DST_DIR/$SET_CONSOLE_FONT_FILE"

# Network

# Configure network
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CONFIGURE_NETWORK_FILE" "$DST_DIR/$CONFIGURE_NETWORK_FILE"

# Bootloader

# Install bootloader
downloadFile "file://$ISO_ARCHCONFIG_PATH/$INSTALL_BOOTLOADER_FILE" "$DST_DIR/$INSTALL_BOOTLOADER_FILE"

# Configure bootloader
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CONFIGURE_BOOTLOADER_FILE" "$DST_DIR/$CONFIGURE_BOOTLOADER_FILE"

# Users

# Set root password
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_ROOT_PASSWORD_FILE" "$DST_DIR/$SET_ROOT_PASSWORD_FILE"

# Add regular user
downloadFile "file://$ISO_ARCHCONFIG_PATH/$ADD_REGULAR_USER_FILE" "$DST_DIR/$ADD_REGULAR_USER_FILE"

# Set regular user password
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_REGULAR_USER_PASSWORD_FILE" "$DST_DIR/$SET_REGULAR_USER_PASSWORD_FILE"

# Set sudoers
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_SUDOERS_FILE" "$DST_DIR/$SET_SUDOERS_FILE"

# Customization

# Update package list
downloadFile "file://$ISO_ARCHCONFIG_PATH/$UPDATE_PACKAGE_LIST_FILE" "$DST_DIR/$UPDATE_PACKAGE_LIST_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$CONFIGURE_PACMAN_FILE" "$DST_DIR/$CONFIGURE_PACMAN_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$INSTALL_PACKAGES_FILE" "$DST_DIR/$INSTALL_PACKAGES_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$LOAD_GUEST_MODULES_FILE" "$DST_DIR/$LOAD_GUEST_MODULES_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$COPY_CONFIG_FILES_FILE" "$DST_DIR/$COPY_CONFIG_FILES_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$INSTALL_DWM_FILE" "$DST_DIR/$INSTALL_DWM_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_TERMINAL_VIDEO_MODE_FILE" "$DST_DIR/$SET_TERMINAL_VIDEO_MODE_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$DISABLE_SYSLINUX_MENU_FILE" "$DST_DIR/$DISABLE_SYSLINUX_MENU_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$SET_EARLY_TERMINAL_FONT_FILE" "$DST_DIR/$SET_EARLY_TERMINAL_FONT_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$RECREATE_IMAGE_FILE" "$DST_DIR/$RECREATE_IMAGE_FILE"

# Config files

downloadFile "file://$ISO_ARCHCONFIG_PATH/$VIRTUALBOX_CONFIG_FILE" "$DST_DIR/$VIRTUALBOX_CONFIG_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$ISSUE_FILE" "$DST_DIR/$ISSUE_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$BASH_PROFILE_FILE" "$DST_DIR/$BASH_PROFILE_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$BASHRC_FILE" "$DST_DIR/$BASHRC_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$GITCONFIG_FILE" "$DST_DIR/$GITCONFIG_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$VIMRC_FILE" "$DST_DIR/$VIMRC_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$VIM_SOLARIZED_FILE" "$DST_DIR/$VIM_SOLARIZED_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$XDEFAULTS_FILE" "$DST_DIR/$XDEFAULTS_FILE"
downloadFile "file://$ISO_ARCHCONFIG_PATH/$XINITRC_FILE" "$DST_DIR/$XINITRC_FILE"

# Change permissions - only needed for user-launched scripts
chmod +x "$GET_DST"
chmod +x "$INSTALL_DST"
chmod +x "$CUSTOMIZE_DST"

